# Generated by Django 4.2 on 2024-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_theme_profile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='private_message',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
