# Generated by Django 4.2 on 2024-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_profile_newsletter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
