from registration.views.signup import Signup
from registration.views.user_update_view import UserUpdateView
from registration.views.password_change_view import CustomPasswordChangeView
from registration.views.password_reset_view import CustomPasswordResetView
from registration.views.password_reset_confirm_view import CustomPasswordResetConfirmView
