# Generated by Django 4.2 on 2024-12-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(max_length=8192),
        ),
    ]
