from forum.views.board_list import BoardList
from forum.views.topic_list import TopicList
from forum.views.topics_most_read import TopicsMostRead
from forum.views.topics_most_answers import TopicsMostAnswers
from forum.views.topics_which_user_replied import TopicsWichUserReplied
from forum.views.topic_detail import TopicDetail
from forum.views.topic_create import TopicCreate
from forum.views.topic_reply import TopicReply
from forum.views.post_edit import PostEdit
from forum.views.last_topic_list import LastTopicsList
from forum.views.last_posts_list import LastPostList
from forum.views.topics_search import TopicSearch
from forum.views.private_message_edit import PrivateMessageEdit
from forum.views.private_message_list import PrivateMessageList
from forum.views.private_message_delete import PrivateMessageDelete
